#!/bin/bash

# Define variables
MODEL_NAME="gpt-oss-spark"

# Check if Modelfile exists (generated by Unsloth)
if [ -f "Modelfile" ]; then
    echo "Found existing Modelfile generated by Unsloth."
else
    echo "Error: Modelfile not found. Please run 'python3 export_to_ollama.py' first."
    exit 1
fi

# Create Ollama model
echo "Creating Ollama model '$MODEL_NAME'..."
ollama create $MODEL_NAME -f Modelfile

echo "Done! You can now run the model with:"
echo "ollama run $MODEL_NAME"
